# Generated by Django 5.2.17 on 2026-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('solar', 'Solar'), ('wind', 'Wind'), ('battery', 'Battery'), ('substation', 'Substation')], max_length=20)),
                ('output', models.CharField(blank=True, max_length=50)),
                ('capacity', models.CharField(blank=True, max_length=50)),
                ('efficiency', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
