# Generated by Django 5.2.17 on 2026-09-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consumption', models.FloatField(default=0)),
                ('efficiency', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low')], default='Normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('consumption', models.FloatField(default=0)),
                ('period', models.CharField(choices=[('week', 'This Week'), ('month', 'This Month'), ('year', 'This Year')], default='week', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
