# Generated by Django 5.2.17 on 2026-09-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_energybuilding_energyreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='energybuilding',
            name='month_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energybuilding',
            name='week_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energybuilding',
            name='year_consumption',
            field=models.FloatField(default=0),
        ),
    ]
